### ISSUE TITLE
No analysis for "†"

### ISSUE THREAD

**Issue by carges** [giellalt/lang-nob#1]
The symbol "†" doesn't get any analysis:
```
echo "†" | hfst-tokenise --print-all --giella-cg --no-weights --unique tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst | vislcg3 --grammar tools/tokenisers/mwe-dis.bin | cg-mwesplit | vislcg3 --grammar src/cg3/disambiguator.bin | vislcg3 --grammar src/cg3/functions.cg3 | vislcg3 --grammar src/cg3/dependency.bin
:†\n
```

**Comment by Trondtr** [comment]
Added it to *.pmscript, give it a try.

**Comment by snomos** [comment]
You added it to sme, while this issue is in nob. Was that intentional?

**Comment by Trondtr** [comment]
Nei, det var feil, eg gjekk automatisk dit fordi Chiara har arbeidd med sme, og oversåg at feilmeldinga var i nob. Skjønt feil og feil, det bör vel inn i alle filene. Eg legg til i nob.

**Comment by carges** [comment]
This is now fixed.
